import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.scss";
import Navbar from "@/sharedComponent/navbar/header";
import Footer from "@/sharedcomponent/footer/footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Navbar />  {/* This will add the navbar on all pages */}
        {children}
<Footer/>
      </body>
    </html>
  );
}


// ls
// git add .next/static/webpack/webpack.1d968e969dd46690.hot-update.js
// git add .next/static/webpack/webpack.209564207b016321.hot-update.js
// git add .
// git status

